name: Build AnkiDroid APK

on:
  push:
    branches: [ mis-mods ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleFullDebug -x test -x lint --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AnkiDroid-debug
          path: AnkiDroid/build/outputs/apk/full/debug/*.apk
